name: Release

on:
  push:
    tags:
      - 'v*'

# https://github.com/astral-sh/trusted-publishing-examples/blob/main/.github/workflows/release.yml
jobs:
  pypi:
    name: Publish to TestPyPI and PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3
      - run: uv build
      # Check that basic features work and we didn't miss to include crucial files
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project -p 3.13 --with dist/*.whl tests/test_edmd.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project -p 3.13 --with dist/*.tar.gz tests/test_edmd.py
      - run: uv publish --publish-url https://test.pypi.org/legacy/ --trusted-publishing always dist/*tar.gz
      - run: uv publish --trusted-publishing always dist/*tar.gz
